// code not seen before starting project

// code add on time 5hr31min31sec

import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class TabWidget extends StatelessWidget {
  const TabWidget(
      {super.key, required this.text, this.style, this.divider}); //isn=

// const TabWidget({  Key? key,  required this.text,  this.style,  this.divider,}) : super(key: key);    // --- generated by dart or flutter extension

  final String text;
  final TextStyle? style;
  final double? divider;

  @override
  Widget build(BuildContext context) {
    return Container(
      margin: const EdgeInsets.symmetric(horizontal: 0),
      width: divider ?? ScreenUtil().screenWidth / 5,
      height: 18,
      child: Center(
          child: Text(
        text,
        style: style ??
            null, // unnecessary use of '??' and 'null' // dart extension
      )),
    );
  }
}
