import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:videosharing/common/utils/kcolors.dart';
import 'package:videosharing/common/widgets/app_style.dart';
import 'package:videosharing/common/widgets/tab_widget.dart';
import 'package:videosharing/src/home/views/home_screen.dart';

class HomeTabs extends StatelessWidget {
  const HomeTabs({super.key, required TabController tabController})
      : _tabController = tabController;

  //  const HomeTabs({  Key? key,  required this._tabController,}) : super(key: key);   // generated by dart or flutter extension sn=

  final TabController _tabController;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 32.h,
      // height: 22.h,
      child: TabBar(
          controller: _tabController,
          indicator: BoxDecoration(
              color: Kolors.kPrimary, borderRadius: BorderRadius.circular(25)),
          labelPadding: EdgeInsets.zero,
          labelColor: Kolors.kWhite,
          dividerColor: Kolors.kPrimaryLight, //sn=
          // dividerColor: Kolors.kGrayLight, //sn=
          // dividerColor: Colors.transparent, //isn=
          tabAlignment: TabAlignment.start,
          isScrollable: true,
          // labelStyle: appStyle(11, Kolors.kPrimary, FontWeight.w600),
          labelStyle: TextStyle(
            fontSize: 11,
            color: Kolors.kPrimary,
            fontWeight: FontWeight.w600,
          ),
          // unselectedLabelStyle: appStyle(11, Kolors.kGray, FontWeight.normal),
          unselectedLabelStyle: TextStyle(
            fontSize: 11,
            color: Kolors.kGray,
            fontWeight: FontWeight.bold, //isn=
            // fontWeight: FontWeight.normal, //isn=
          ),
          tabs: List.generate(
            homeTabs.length,
            (i) => Tab(
              child: TabWidget(
                text: homeTabs[i],
              ),
            ),
          )),
    );
  }
}
